services:
  selenoid:
    image: aerokube/selenoid:latest-release
    ports:
      - "4444:4444"
    volumes:
      - ./selenoid:/etc/selenoid
      - ./video:/opt/selenoid/video
      - /var/run/docker.sock:/var/run/docker.sock
    command: [
      "-conf", "/etc/selenoid/browsers.json",
      "-limit", "5",
      "-container-network", "demo_default",
      "-video-output-dir", "/opt/selenoid/video"
    ]

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    ports:
      - "8081:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    depends_on:
      - selenoid

networks:
  default:
    name: demo_default
